### ISSUE TITLE
Build failed for osx R 3.4.1

### ISSUE THREAD

**Issue by jdblischak** [conda-forge/r-ggplot2-feedstock#2]
ggplot2 failed to build on osx for R 3.4.1. It pulled both r-rlang and r-tibble from defaults, so I assume that was what caused the error.

https://travis-ci.org/conda-forge/r-ggplot2-feedstock/jobs/265609030#L242
https://travis-ci.org/conda-forge/r-ggplot2-feedstock/jobs/265609030#L246

Both r-rlang and r-tibble have since been added to conda-forge, so I restarted the build.

https://github.com/conda-forge/r-rlang-feedstock
https://github.com/conda-forge/r-tibble-feedstock

I also suspect that the missing ggplot2 dependency on osx for R 3.4.1 is responsible for the downstream failure to build on osx for R 3.4.1 for multiple packages, e.g.:

https://github.com/conda-forge/r-hmisc-feedstock
https://github.com/conda-forge/r-viridis-feedstock

And then those that depend on them, etc.

My current PR in staged-recipes includes r-rms, which depends on r-hmisc:

https://github.com/conda-forge/staged-recipes/pull/3983

ggplot2 has many reverse imports/depends, so this could be a lot of work depending on how many have been added to conda-forge.

https://cran.r-project.org/package=ggplot2

**Comment by bgruening** [comment]
:( yes, this is somehow expected in conda-forge and if we create PRs with more then one recipe. I'm still going through all the recipes and retriggering builds if I find them. Thanks for the list. Restarting should help.

**Comment by jdblischak** [comment]
> this is somehow expected in conda-forge and if we create PRs with more then one recipe. I'm still going through all the recipes and retriggering builds if I find them.

Yeah, I guess this situation is inevitable. `conda build-all` builds each recipe in the correct order for the PR to staged-recipes, but then the order is randomized (or maybe alphabetical?) when feedstocks get created and CI builds started.

> Thanks for the list. Restarting should help.

OK. r-ggplot2 is now available. On to its dependencies...

https://anaconda.org/conda-forge/r-ggplot2/files
